#!/usr/bin/env node

/**
 * Onyka — Interactive Configuration (pnpm configure)
 * Creates apps/server/.env with generated secrets and SMTP preferences.
 * Optional — secrets are auto-generated on first start without this.
 */

import { createInterface } from 'readline'
import { randomBytes } from 'crypto'
import { existsSync, writeFileSync, readFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import { execSync } from 'child_process'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT_DIR = join(__dirname, '..')
const ENV_PATH = join(ROOT_DIR, 'apps', 'server', '.env')

const rl = createInterface({ input: process.stdin, output: process.stdout })
const ask = (q) => new Promise((resolve) => rl.question(q, resolve))

function log(msg = '') {
  console.log(`  ${msg}`)
}

function header() {
  console.log('')
  log('\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557')
  log('\u2551         Onyka \u2014 Configuration        \u2551')
  log('\u255a\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255d')
  console.log('')
}

async function confirmOverwrite() {
  if (!existsSync(ENV_PATH)) return true

  const answer = await ask('  .env exists already. Overwrite? (y/N) ')
  if (answer.trim().toLowerCase() !== 'y') {
    log('Cancelled.')
    return false
  }
  return true
}

async function askEmail() {
  console.log('')
  log('? Configure email? (for password reset, 2FA)')
  log('  (1) No \u2014 later')
  log('  (2) Yes \u2014 SMTP provider')
  const choice = await ask('  > ')

  if (choice.trim() === '2') {
    console.log('')
    const host = await ask('  SMTP Host: ')
    const port = (await ask('  SMTP Port (587): ')) || '587'
    const user = await ask('  SMTP User: ')
    const pass = await ask('  SMTP Pass: ')
    const secure = (await ask('  SMTP Secure (false): ')) || 'false'
    const from =
      (await ask('  SMTP From (Onyka <noreply@example.com>): ')) ||
      'Onyka <noreply@example.com>'
    return {
      host: host.trim(),
      port: port.trim(),
      user: user.trim(),
      pass: pass.trim(),
      secure: secure.trim(),
      from: from.trim(),
    }
  }

  return null
}

function buildEnvContent({ jwtSecret, encryptionKey, smtp }) {
  const lines = [
    '# ======================================================================',
    '#  ONYKA \u2014 Generated by `pnpm configure`',
    '#',
    `#  Created: ${new Date().toISOString().split('T')[0]}`,
    '# ======================================================================',
    '',
    '# Server',
    'NODE_ENV=development',
    'PORT=3001',
    '',
    '# Database',
    'DATABASE_URL=./data/onyka.db',
    '',
    '# Authentication',
    `JWT_SECRET=${jwtSecret}`,
    '',
    '# Encryption at rest',
    '# WARNING: Without this key, encrypted data is PERMANENTLY UNRECOVERABLE.',
    '# Always back up this file alongside your database.',
    `ENCRYPTION_KEY=${encryptionKey}`,
    '',
    '# Network',
    'CORS_ORIGIN=http://localhost:5173',
    'FRONTEND_URL=http://localhost:5173',
  ]

  if (smtp) {
    lines.push(
      '',
      '# Email / SMTP',
      `SMTP_HOST=${smtp.host}`,
      `SMTP_PORT=${smtp.port}`,
      `SMTP_USER=${smtp.user}`,
      `SMTP_PASS=${smtp.pass}`,
      `SMTP_SECURE=${smtp.secure}`,
      `SMTP_FROM=${smtp.from}`
    )
  }

  lines.push('')
  return lines.join('\n')
}

async function main() {
  header()

  if (!(await confirmOverwrite())) {
    rl.close()
    process.exit(0)
  }

  const jwtSecret = randomBytes(48).toString('base64url')
  const encryptionKey = randomBytes(32).toString('hex')

  log('\u2713 JWT_SECRET generated (48 bytes)')
  log('\u2713 ENCRYPTION_KEY generated (32 bytes)')
  console.log('')

  const smtp = await askEmail()

  const content = buildEnvContent({
    jwtSecret,
    encryptionKey,
    smtp,
  })

  writeFileSync(ENV_PATH, content, 'utf-8')

  console.log('')
  log('\u2713 .env created: apps/server/.env')

  // Build the project
  console.log('')
  log('Building project...')
  console.log('')
  try {
    execSync('pnpm build', { cwd: ROOT_DIR, stdio: 'inherit' })
    log('\u2713 Build complete')
  } catch {
    console.log('')
    log('[ERROR] Build failed. Fix errors above, then run: pnpm build')
    rl.close()
    process.exit(1)
  }

  // Run database migrations (use compiled migrate.js which auto-creates data dir)
  console.log('')
  log('Running database migrations...')
  try {
    execSync('node apps/server/dist/db/migrate.js', { cwd: ROOT_DIR, stdio: 'inherit' })
    log('\u2713 Database ready')
  } catch {
    console.log('')
    log('[ERROR] Migration failed. Run manually: node apps/server/dist/db/migrate.js')
    rl.close()
    process.exit(1)
  }

  console.log('')
  log('\u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510')
  log('\u2502  Ready! Start Onyka:                        \u2502')
  log('\u2502                                              \u2502')
  log('\u2502  Development:  pnpm dev                      \u2502')
  log('\u2502  Production:   pnpm start:prod               \u2502')
  log('\u2502  Docker:       cd docker && docker compose up \u2502')
  log('\u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518')
  console.log('')
  log('\u26a0\ufe0f  ENCRYPTION_KEY saved in .env')
  log('   Never lose this key \u2014 your data depends on it.')
  console.log('')

  rl.close()
}

main().catch((err) => {
  console.error('Setup failed:', err.message)
  rl.close()
  process.exit(1)
})
